language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get update
  - chmod +x mvnw
  - echo "Let's start Maven Package!"
  - mvn clean install
  - mvn -N io.takari:maven:wrapper
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag docker-to-aws-with-java:latest smaceno/docker-to-aws-with-java:latest;
    docker push smaceno/docker-to-aws-with-java;
  on:
    branch: master
notifications:
  email: false